main.exe: main.o funTempArray.o funArea.o funHello.o
	gcc -o main.exe main.o funTempArray.o funArea.o funHello.o

main.o: main.c
	gcc -c main.c

funTempArray.o: funTempArray.c
	gcc -c funTempArray.c

funArea.o: funArea.c
	gcc -c funArea.c

funHello.o: funHello.c
	gcc -c funHello.c
